version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: Capstone
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root1234
    ports:
      - 80:80

volumes:
  postgres-data:
