const citiesInThailand = [
    { label: "Bangkok", value: "Bangkok" },
    { label: "Chiang Mai", value: "Chiang Mai" },
    { label: "Phuket", value: "Phuket" },
    { label: "Pattaya", value: "Pattaya" },
    { label: "Ayutthaya", value: "Ayutthaya" },
    { label: "Hua Hin", value: "Hua Hin" },
    { label: "Khon Kaen", value: "Khon Kaen" },
    { label: "Nakhon Ratchasima", value: "Nakhon Ratchasima" },
    { label: "Udon Thani", value: "Udon Thani" },
    { label: "Surat Thani", value: "Surat Thani" },
    { label: "Hat Yai", value: "Hat Yai" },
    { label: "Chiang Rai", value: "Chiang Rai" },
    { label: "Nakhon Si Thammarat", value: "Nakhon Si Thammarat" },
    { label: "Phetchaburi", value: "Phetchaburi" },
    { label: "Krabi", value: "Krabi" },
    { label: "Rayong", value: "Rayong" },
    { label: "Trang", value: "Trang" },
    { label: "Ubon Ratchathani", value: "Ubon Ratchathani" },
    { label: "Lampang", value: "Lampang" },
    { label: "Sukhothai", value: "Sukhothai" },
    { label: "Mae Hong Son", value: "Mae Hong Son" },
    { label: "Phitsanulok", value: "Phitsanulok" },
    { label: "Loei", value: "Loei" },
    { label: "Chonburi", value: "Chonburi" },
    { label: "Chanthaburi", value: "Chanthaburi" },
    { label: "Ratchaburi", value: "Ratchaburi" },
    { label: "Samut Prakan", value: "Samut Prakan" },
    { label: "Pathum Thani", value: "Pathum Thani" },
    { label: "Nakhon Pathom", value: "Nakhon Pathom" },
    { label: "Samut Sakhon", value: "Samut Sakhon" },
    { label: "Nonthaburi", value: "Nonthaburi" },
    { label: "Chachoengsao", value: "Chachoengsao" },
    { label: "Phetchabun", value: "Phetchabun" },
    { label: "Trat", value: "Trat" },
    { label: "Kanchanaburi", value: "Kanchanaburi" },
    { label: "Yala", value: "Yala" },
    { label: "Narathiwat", value: "Narathiwat" },
    { label: "Prachuap Khiri Khan", value: "Prachuap Khiri Khan" },
    { label: "Nakhon Phanom", value: "Nakhon Phanom" },
    { label: "Mukdahan", value: "Mukdahan" },
    { label: "Sakon Nakhon", value: "Sakon Nakhon" },
    { label: "Chaiyaphum", value: "Chaiyaphum" },
    { label: "Buriram", value: "Buriram" },
    { label: "Si Sa Ket", value: "Si Sa Ket" },
    { label: "Roi Et", value: "Roi Et" },
    { label: "Yasothon", value: "Yasothon" },
    { label: "Amnat Charoen", value: "Amnat Charoen" },
    { label: "Kalasin", value: "Kalasin" },
    { label: "Surin", value: "Surin" },
    { label: "Satun", value: "Satun" },
    { label: "Phayao", value: "Phayao" },
    { label: "Lamphun", value: "Lamphun" },
    { label: "Nan", value: "Nan" },
    { label: "Phrae", value: "Phrae" },
    { label: "Tak", value: "Tak" },
    { label: "Kamphaeng Phet", value: "Kamphaeng Phet" },
    { label: "Nakhon Sawan", value: "Nakhon Sawan" },
    { label: "Uthai Thani", value: "Uthai Thani" },
    { label: "Chumphon", value: "Chumphon" },
    { label: "Ranong", value: "Ranong" },
    { label: "Phang Nga", value: "Phang Nga" },
    { label: "Phatthalung", value: "Phatthalung" },
    { label: "Samut Songkhram", value: "Samut Songkhram" },
    { label: "Sing Buri", value: "Sing Buri" },
    { label: "Ang Thong", value: "Ang Thong" },
    { label: "Saraburi", value: "Saraburi" },
    { label: "Sa Kaeo", value: "Sa Kaeo" },
    { label: "Prachinburi", value: "Prachinburi" },
    { label: "Nong Bua Lam Phu", value: "Nong Bua Lam Phu" },
    { label: "Nong Khai", value: "Nong Khai" },
    { label: "Chai Nat", value: "Chai Nat" },
    { label: "Suphan Buri", value: "Suphan Buri" },
    { label: "Phichit", value: "Phichit" },
    { label: "Phrae", value: "Phrae" },
];

export default citiesInThailand;
