 const options = [
    { label: "Specialization", value: "Specialization" },
    { label: "Quantum Computing", value: "Quantum Computing" },
    { label: "Cryptography", value: "Cryptography" },
    { label: "Cloud Computing", value: "Cloud Computing" },
    { label: "Web Development", value: "Web Development" },
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    { label: "Robotics", value: "Robotics" },
    { label: "IoT", value: "IoT" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "C++", value: "C++" },
    { label: "Algorithms", value: "Algorithms" },
    { label: "Data Structures", value: "Data Structures" },
    { label: "AWS", value: "AWS" },
    { label: "Azure", value: "Azure" },
    { label: "Google Cloud Platform", value: "Google Cloud Platform" },
    { label: "Software Testing", value: "Software Testing" },
    { label: "QA", value: "QA" },
    { label: "iOS Development", value: "iOS Development" },
    { label: "Android Development", value: "Android Development" },
    { label: "Swift", value: "Swift" },
    { label: "Kotlin", value: "Kotlin" },
    { label: "Blockchain", value: "Blockchain" },
    { label: "Healthcare", value: "Healthcare" },
    { label: "Home Automation", value: "Home Automation" },
    { label: "Big Data", value: "Big Data" },
    { label: "Data Visualization", value: "Data Visualization" },
    { label: "DevOps", value: "DevOps" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "Continuous Integration", value: "Continuous Integration" },
    { label: "Continuous Deployment", value: "Continuous Deployment" },
    { label: "Backend Development", value: "Backend Development" },
    { label: "Node.js", value: "Node.js" },
    { label: "Socket.io", value: "Socket.io" },
    { label: "Java", value: "Java" },
    { label: "Spring Boot", value: "Spring Boot" },
    { label: "MySQL", value: "MySQL" },
    { label: "UX", value: "UX" },
    { label: "UI Design", value: "UI Design" },
    { label: "Python", value: "Python" },
    { label: "TensorFlow", value: "TensorFlow" },
    { label: "Data Science", value: "Data Science" },
    { label: "Machine Learning", value: "Machine Learning" },
    { label: "Learning Analytics", value: "Learning Analytics" },
    { label: "Angular", value: "Angular" },
    { label: "Microservices", value: "Microservices" },
    { label: "Hadoop", value: "Hadoop" },
    { label: "Spark", value: "Spark" },
    { label: "Embedded Systems", value: "Embedded Systems" },
    { label: "Firmware Engineering", value: "Firmware Engineering" },
    { label: "Data Mining", value: "Data Mining" },
    { label: "Predictive Analytics", value: "Predictive Analytics" },
    { label: "Experimental Design", value: "Experimental Design" },
    { label: "Web Scraping", value: "Web Scraping" },
    { label: "Desktop Development", value: "Desktop Development" },
    { label: "Django", value: "Django" },
    { label: "Migration", value: "Migration" },
    { label: "E-commerce", value: "E-commerce" },
    { label: "Big Data Technologies", value: "Big Data Technologies" },
    { label: "Data Engineering", value: "Data Engineering" },
    { label: "Marketing Analytics", value: "Marketing Analytics" },
    { label: "SEO", value: "SEO" },
    { label: "Health Tech", value: "Health Tech" },
    { label: "Network Security", value: "Network Security" },
    { label: "Compliance", value: "Compliance" },
    { label: "Augmented Reality", value: "Augmented Reality" },
    { label: "Creative Design", value: "Creative Design" },
    { label: "Financial Analysis", value: "Financial Analysis" },
    { label: "Mobile Development", value: "Mobile Development" },
    { label: "CRM Development", value: "CRM Development" },
    { label: "Software Integration", value: "Software Integration" },
    { label: "SQL", value: "SQL" },
    { label: "Virtual Reality", value: "Virtual Reality" },
    { label: "3D Modeling", value: "3D Modeling" },
    { label: "Unity", value: "Unity" },
    { label: "Smart Contracts", value: "Smart Contracts" },
    { label: "R", value: "R" },
    { label: "Video Streaming", value: "Video Streaming" },
    { label: "Game Development", value: "Game Development" },
    { label: "Animation", value: "Animation" },
    { label: "Gamification", value: "Gamification" },
    { label: "ROS", value: "ROS" },
    { label: "SaaS", value: "SaaS" },
    { label: "Physics", value: "Physics" },
    { label: "Mathematics", value: "Mathematics" },
    { label: "Telehealth", value: "Telehealth" },
    { label: "Health IT", value: "Health IT" },
    { label: "Recommendation Systems", value: "Recommendation Systems" },
    { label: "Energy Management", value: "Energy Management" },
    { label: "NLP", value: "NLP" },
    { label: "Social Media Analysis", value: "Social Media Analysis" },
    { label: "React", value: "React" },
  ];
  export default options;