import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import  NewNav  from "./components/NewNav";
import { Noto_Sans_Thai } from "next/font/google";
import SessionProvider from "./components/SessionProvider/SessionProvider"
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "300"
});
const noto_sans_thai = Noto_Sans_Thai({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by xcreate next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
  {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={noto_sans_thai.className}>
        <SessionProvider session={session}>
          <NewNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
