import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import  NewNav  from "./components/NewNav";
import { Noto_Sans_Thai } from "next/font/google";
import SessionProvider from "./components/sessionProvider";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "300"
});
const noto_sans_thai = Noto_Sans_Thai({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by xcreate next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <SessionProvider>
    
     <body className={noto_sans_thai.className}>
     <NewNav />
        {children}
        <Footer />
      </body>

     </SessionProvider>
    </html>
  );
}
