-- AlterTable
ALTER TABLE "user" ALTER COLUMN "first_name" DROP DEFAULT,
ALTER COLUMN "last_name" DROP DEFAULT,
ALTER COLUMN "username" DROP DEFAULT,
ALTER COLUMN "image" DROP DEFAULT,
ALTER COLUMN "phone_number" DROP DEFAULT,
ALTER COLUMN "id_card" DROP DEFAULT;
